export const PERMISSIONS = {
  CUSTOMERS_READ: 'customers:read',
  CUSTOMERS_WRITE: 'customers:write',
  ENQUIRIES_READ: 'enquiries:read',
  ENQUIRIES_WRITE: 'enquiries:write',
  PROJECTS_READ: 'projects:read',
  PROJECTS_WRITE: 'projects:write',
  DRAWINGS_READ: 'drawings:read',
  DRAWINGS_WRITE: 'drawings:write',
  DUCT_SCHEDULES_READ: 'duct_schedules:read',
  DUCT_SCHEDULES_WRITE: 'duct_schedules:write',
  QUOTATIONS_READ: 'quotations:read',
  QUOTATIONS_WRITE: 'quotations:write',
  POS_READ: 'pos:read',
  POS_WRITE: 'pos:write',
  ORDERS_READ: 'orders:read',
  ORDERS_WRITE: 'orders:write',
  MANUFACTURING_READ: 'manufacturing:read',
  MANUFACTURING_WRITE: 'manufacturing:write',
  DISPATCHES_READ: 'dispatches:read',
  DISPATCHES_WRITE: 'dispatches:write',
  DISPATCHES_CANCEL: 'dispatches:cancel',
  REPORTS_READ: 'reports:read',
  USERS_MANAGE: 'users:manage',
  WORKFLOW_MANAGE: 'workflow:manage',
  SETTINGS_MANAGE: 'settings:manage',
} as const

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS]

export const ROLE_DEFINITIONS = {
  ADMIN: {
    name: 'Administrator',
    description: 'Full system access',
    permissions: Object.values(PERMISSIONS),
  },
  SUPERVISOR: {
    name: 'Supervisor',
    description: 'Oversight — dashboard, full workflow visibility, no user admin',
    permissions: [
      PERMISSIONS.CUSTOMERS_READ,
      PERMISSIONS.CUSTOMERS_WRITE,
      PERMISSIONS.ENQUIRIES_READ,
      PERMISSIONS.ENQUIRIES_WRITE,
      PERMISSIONS.PROJECTS_READ,
      PERMISSIONS.PROJECTS_WRITE,
      PERMISSIONS.QUOTATIONS_READ,
      PERMISSIONS.QUOTATIONS_WRITE,
      PERMISSIONS.POS_READ,
      PERMISSIONS.POS_WRITE,
      PERMISSIONS.ORDERS_READ,
      PERMISSIONS.ORDERS_WRITE,
      PERMISSIONS.MANUFACTURING_READ,
      PERMISSIONS.MANUFACTURING_WRITE,
      PERMISSIONS.DISPATCHES_READ,
      PERMISSIONS.DISPATCHES_WRITE,
      PERMISSIONS.DISPATCHES_CANCEL,
      PERMISSIONS.REPORTS_READ,
      PERMISSIONS.SETTINGS_MANAGE,
    ],
  },
  SALES: {
    name: 'Sales',
    description: 'CRM, enquiries, quotations',
    permissions: [
      PERMISSIONS.CUSTOMERS_READ,
      PERMISSIONS.CUSTOMERS_WRITE,
      PERMISSIONS.ENQUIRIES_READ,
      PERMISSIONS.ENQUIRIES_WRITE,
      PERMISSIONS.PROJECTS_READ,
      PERMISSIONS.QUOTATIONS_READ,
      PERMISSIONS.QUOTATIONS_WRITE,
      PERMISSIONS.POS_READ,
      PERMISSIONS.POS_WRITE,
      PERMISSIONS.ORDERS_READ,
      PERMISSIONS.REPORTS_READ,
    ],
  },
  DESIGNER: {
    name: 'Designer',
    description: 'Client drawings, duct Excel import, handover to accounts',
    permissions: [
      PERMISSIONS.PROJECTS_READ,
      PERMISSIONS.DRAWINGS_READ,
      PERMISSIONS.DRAWINGS_WRITE,
      PERMISSIONS.DUCT_SCHEDULES_READ,
      PERMISSIONS.DUCT_SCHEDULES_WRITE,
      PERMISSIONS.ENQUIRIES_READ,
      PERMISSIONS.ENQUIRIES_WRITE,
    ],
  },
  PRODUCTION: {
    name: 'Production',
    description: 'Shop floor — production approval and ready stock',
    permissions: [
      PERMISSIONS.ORDERS_READ,
      PERMISSIONS.MANUFACTURING_READ,
      PERMISSIONS.MANUFACTURING_WRITE,
      PERMISSIONS.ENQUIRIES_READ,
    ],
  },
  DISPATCHER: {
    name: 'Dispatcher',
    description: 'Create and manage vehicle dispatches',
    permissions: [
      PERMISSIONS.ORDERS_READ,
      PERMISSIONS.DISPATCHES_READ,
      PERMISSIONS.DISPATCHES_WRITE,
      PERMISSIONS.REPORTS_READ,
    ],
  },
  /** @deprecated Use DISPATCHER — kept so older JWTs / seeds still authorize. */
  DISPATCH: {
    name: 'Dispatch Operator',
    description: 'Alias for DISPATCHER',
    permissions: [
      PERMISSIONS.ORDERS_READ,
      PERMISSIONS.DISPATCHES_READ,
      PERMISSIONS.DISPATCHES_WRITE,
      PERMISSIONS.REPORTS_READ,
    ],
  },
  ACCOUNTS: {
    name: 'Accounts',
    description: 'PO processing, approval workflow, return enquiries to design',
    permissions: [
      PERMISSIONS.ENQUIRIES_READ,
      PERMISSIONS.ENQUIRIES_WRITE,
      PERMISSIONS.POS_READ,
      PERMISSIONS.POS_WRITE,
      PERMISSIONS.REPORTS_READ,
    ],
  },
} as const
